/**
 * This file was generated by the Jeddict
 */
package domain;

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

/**
 * @author Daniel Lindkvist
 */
@Entity
public class Media implements Comparable<Media> {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @NotNull
    private Long id;

    @Basic
    private String title;

    @Basic
    private Integer year;

    @Basic
    @Min(value = 1)
    @Max(value = 5)
    private int mediacondition = 0;

    @Basic
    @Min(value = 1)
    @Max(value = 5)
    private int rating;

    @Basic
    @Temporal(TemporalType.DATE)
    private Date cleaning_date;

    @ManyToOne
    private Artist artist;

    @ManyToOne
    private Mediatype mediatype;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Integer getYear() {
        return this.year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }

    public int getMediacondition() {
        return this.mediacondition;
    }

    public void setMediacondition(int mediacondition) {
        this.mediacondition = mediacondition;
    }

    public int getRating() {
        return this.rating;
    }

    public void setRating(int rating) {
        this.rating = rating;
    }

    public Date getCleaning_date() {
        return this.cleaning_date;
    }

    public void setCleaning_date(Date cleaning_date) {
        this.cleaning_date = cleaning_date;
    }

    public Artist getArtist() {
        return this.artist;
    }

    public void setArtist(Artist artist) {
        this.artist = artist;
    }

    public Mediatype getMediatype() {
        return this.mediatype;
    }

    public void setMediatype(Mediatype mediatype) {
        this.mediatype = mediatype;
    }

    @Override
    public int compareTo(Media o) {
        return this.getTitle().compareTo(o.getTitle());
    }

    @Override
    public String toString() {
        return artist.getName() + " : " + title;
    }

    public String render() {
        return "Id: " + id +
                "\nMediatyp: " + mediatype.getType() +
                "\nTitel: " + title +
                "\nArtist: " + artist.getName() +
                "\nÅr: " + year + 
                "\nSkick: " + mediacondition +
                "\nBetyg: " + rating;
                
                
    }
    
    
    

}